version: "3.8"

services:
  web:
    build:
        context: DOCKER_IMAGE_NAME:latest
    env_file:
        - .env
    expose:
        - 8000
    volumes:
      - static_volume:/bizeducate_app/web/staticfiles
      - media_volume:/bizeducate_app/web/media

    command: gunicorn bizeducate_app.wsgi:application --bind 0.0.0.0:8000

    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.18
    restart: always
    env_file:
        - .env
    ports:
        - "5432:5432"
    volumes:
        - my_db:$PGDATA

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/bizeducate_app/web/staticfiles
      - media_volume:/bizeducate_app/web/media
      - /etc/letsencrypt/live/bizeducate.com/fullchain.pem:/etc/letsencrypt/live/bizeducate.com/fullchain.pem
      - /etc/letsencrypt/live/bizeducate.com/privkey.pem:/etc/letsencrypt/live/bizeducate.com/privkey.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
    my_db:
    static_volume:
    media_volume:
