version: "1"

services:
  web:
    build:
        context: .
    env_file:
        - .env
    expose:
        - 8000

    command: gunicorn bizeducate_app.wsgi:application --bind 0.0.0.0:8000

    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.18
    restart: always
    env_file:
        - .env
    ports:
        - "5432:5432"
    volumes:
        - my_db:$PGDATA

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
    my_db:
