# Generated by Django 4.2.13 on 2024-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="key_questions",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcome",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="overview",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="profile",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
