# Generated by Django 4.2.9 on 2024-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
