# Generated by Django 4.2.13 on 2025-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_course_key_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="learning_outcome",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
