# Generated by Django 4.2.9 on 2024-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_trainer_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='key_questions',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcome',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
