# Generated by Django 4.2.13 on 2025-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_course_learning_outcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="audience",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
