# Generated by Django 4.2.13 on 2025-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_course_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="key_questions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcome",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="course",
            name="overview",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="profile",
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
