# Generated by Django 4.2.13 on 2025-05-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_course_key_questions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="key_questions",
        ),
        migrations.AlterField(
            model_name="course",
            name="audience",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="CourseKeyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_questions",
                        to="website.course",
                    ),
                ),
            ],
        ),
    ]
