# Generated by Django 4.2.9 on 2024-02-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='website.venue'),
        ),
    ]
