# Generated by Django 4.2.13 on 2025-05-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_remove_course_key_questions_alter_course_audience_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursekeyquestion",
            old_name="text",
            new_name="question",
        ),
        migrations.RemoveField(
            model_name="course",
            name="audience",
        ),
        migrations.CreateModel(
            name="CourseAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audience", models.TextField(max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="website.course",
                    ),
                ),
            ],
        ),
    ]
