# Generated by Django 4.2.9 on 2024-02-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_author_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='company',
        ),
        migrations.RemoveField(
            model_name='author',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='position',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
    ]
