# Generated by Django 4.2.9 on 2024-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_author_testimonial_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='author_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
