# Generated by Django 4.2.9 on 2024-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_testimonial_author_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_company_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_position',
            field=models.CharField(max_length=255),
        ),
    ]
