name: Docker-GCP-CI-CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test --keepdb
          
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest \
            --build-arg SECRET_KEY=$SECRET_KEY \
            --build-arg ENVIRONMENT=$ENVIRONMENT \
            --no-cache

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_STAGING }}:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          export_default_credentials: true

      - name: Access gcloud CLI
        run: |
          gcloud auth configure-docker

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker-compose.yml
        run: |
          sed "s/DOCKER_IMAGE_NAME_STAGING/${{secrets.DOCKERHUB_USERNAME}}\/${{secrets.DOCKER_IMAGE_NAME_STAGING}}/g" docker-compose-template.yml > docker-compose.yml
          sed -i "s/DOCKER_IMAGE_NAME/${{secrets.DOCKERHUB_USERNAME}}\/${{secrets.DOCKER_IMAGE_NAME}}/g" docker-compose.yml
          sed -i "s/DOCKER_CONTAINER_NAME_STAGING/${{secrets.DOCKER_CONTAINER_NAME_STAGING}}/g" docker-compose.yml
          sed -i "s/DOCKER_CONTAINER_NAME/${{secrets.DOCKER_CONTAINER_NAME}}/g" docker-compose.yml


      - name: scp into GCP instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP_STAGING }}
          username: ${{ secrets.GCE_SSH_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.GCE_SSH_USERNAME }}/"

      - name: SSH into GCP instance and deploy Django
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP_STAGING }}
          username: ${{ secrets.GCE_SSH_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yml --profile staging down
            docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yml --profile staging build --pull
            docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yml --profile staging up -d

            docker image prune -f
  
